######################################################
##                                                  ##
##                    Set Ranks                     ##
##                Developed by reussy               ##
##                                                  ##
######################################################

# Yaml Validator: https://yamlchecker.com/
# Yaml Formatter: https://codebeautify.org/yaml-validator
# Format for gradients: "<GRADIENT:2C08BA>&lText here</GRADIENT:028A97>"
# Format for default rainbow: "<RAINBOW1>Text here</RAINBOW>"
# Format for solid colors: "<SOLID:FF0080>Text here"

storage:

  # The hostname of the database server.
  address: "localhost"

  # The port of the database server.
  port: 3306

  # The name of the database where the data should be stored.
  database: "exodus"

  # The username property for the database connection.
  username: "root"

  # The password property for the database connection.
  password: "password"

  # Use SSL for the database connection.
  useSSL: false

general:

  # The debug mode is used to show more information
  # about the plugin. It is recommended to enable
  # if you are having issues with the plugin,
  # or you are about to report an error.
  debug: true

# Category for sounds.
# Leave empty to disable the sound.
# The format is: "SOUND:VOLUME:PITCH"
# - SOUND: The sound to play.
# - VOLUME: The volume of the sound.
# - PITCH: The pitch of the sound.
sounds:

  # The sound to play when the player toggles the chat channel.
  toggle-chat-channel: "BLOCK_NOTE_BLOCK_PLING:1:1"

# Category of some general settings for the menus.
menus:

  # The items for navigation in the menus.
  navigation-items:

    # The item for the next page.
    # The position of the item is determined in each menu.
    next-page-item:

      # The material of the item.
      # - Use "PLAYER_HEAD" to make it a player head.
      material: "PLAYER_HEAD"

      # The texture of the item.
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTliZjMyOTJlMTI2YTEwNWI1NGViYTcxM2FhMWIxNTJkNTQxYTFkODkzODgyOWM1NjM2NGQxNzhlZDIyYmYifX19"

      # The display name of the item.
      display-name: '&b► &fNext Page'

      # The lore of the item.
      description:
        - '&r'
        - '&f► &3Click to go to the next page'

    # The item for the previous page.
    # The position of the item is determined in each menu.
    previous-page-item:

      # The material of the item.
      # - Use "PLAYER_HEAD" to make it a player head.
      material: "PLAYER_HEAD"

      # The texture of the item.
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmQ2OWUwNmU1ZGFkZmQ4NGU1ZjNkMWMyMTA2M2YyNTUzYjJmYTk0NWVlMWQ0ZDcxNTJmZGM1NDI1YmMxMmE5In19fQ=="

      # The display name of the item.
      display-name: '&b► &fPrevious Page'

      # The lore of the item.
      description:
        - '&r'
        - '&f► &3Click to go to the previous page'

    # The item for the back menu.
    # The position of the item is determined in each menu.
    back-item:

      # The material of the item.
      # - Use "PLAYER_HEAD" to make it a player head.
      material: "PLAYER_HEAD"

      # The texture of the item.
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmQ2OWUwNmU1ZGFkZmQ4NGU1ZjNkMWMyMTA2M2YyNTUzYjJmYTk0NWVlMWQ0ZDcxNTJmZGM1NDI1YmMxMmE5In19fQ=="

      # The display name of the item.
      display-name: '&b► &fBack'

      # The lore of the item.
      description:
        - '&r'
        - '&f► &3Click to back to the previous menu'

commands:

  # The command to use different sub-commands.
  main-command: "sr"

  # The command to open the groups menu and manage them.
  rank: "rank"

  # The command to set the rank of a player.
  set-rank: "setrank"

  # The command to promote a player.
  promote: "promote"

  # The command to perform a grant action.
  grant: "grant"

  # The command to perform an un-grant action.
  ungrant: "ungrant"

  # The command to open the grant history menu.
  grant-history: "granth"

  # The command to clear the grant history of a player.
  clear-grant-history: "cleargranthistory"

  # The command to open the users menu and manage them.
  user: "user"

messages:
  prefix: "&8[&cSR&8] "

  plugin-reloaded: "&aThe plugin has been reloaded successfully."

  only-console: "&cThis command can only be executed by the console."

  must-be-player: "&cYou must be a player to execute this command."

  player-not-found: "&cThis player is offline or does not exist."

  you-cant-use-yourself: "&cYou can't use this on yourself."

  no-permission: "&cYou don't have the required permissions for this action."

  set-rank:
    usage: "&cUsage: /setrank <player> <rank> [duration]"
    rank-not-found: "&cThis rank does not exist."
    invalid-duration: "&cPlease enter a valid duration, or leave it empty for permanent."
    already-in-group: "&cThis player is already has this rank."
    success: "&aThe rank &6{GROUP_NAME} &ahas been set to &6{PLAYER_NAME} &afor &6{DURATION}&a."

  promote:
    usage: "&cUsage: /promote <player> <track>"
    unknown-track: "&cThis track does not exist."
    no-tracks: "&cThere are no tracks available. Use /lp createtrack <name> to create one."
    already-in-group: "&cThis player is already in this group."
    success: "&aSuccessfully promoted &6{PLAYER_NAME} &ato rank &6{GROUP_NAME}&a."
    failed: "&cFailed to promote &6{PLAYER_NAME} &ato rank &6{GROUP_NAME}&c."

  grant:
    grant-usage: "&cUsage: /grant <player> <rank> <reason>"
    ungrant-usage: "&cUsage: /ungrant <id> <reason>"
    grant-history-usage: "&cUsage: /granth <player>"
    clear-grant-history-usage: "&cUsage: /cleargranthistory <player>"
    no-history: "&cThis player does not have any grant history."
    grant-history-cleared: "&aThe grant history of &6{PLAYER_NAME} &ahas been cleared."
    grant-created: "&aThe grant has been created successfully for &6{PLAYER_NAME} &awith the rank &6{GROUP_NAME} &aand reason &6{REASON}&a."
    grant-not-found: "&cThis grant does not exist."
    ungrant-created: "&aThe grant {GRANT_ID} has been ungranted successfully for &6{PLAYER_NAME} &awith the rank &6{GROUP_NAME} &aand reason &6{REASON}&a."